name: This is github acount
run-name: this is the run name
on: [main]
jobs: 
  Echo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: cat temp.txt
        run: cat temp.txt
